"""Per-language Dockerfile text generators (no filesystem I/O)."""

from __future__ import annotations

import json

from app.core.enums import SupportedLanguage
from app.core.exceptions import DockerfileGenerationError
from app.core.models import BuildOverride, ProjectInfo

_GO_VERSION_DEFAULT = "1.23"
_PYTHON_VERSION_DEFAULT = "3.12"
_NODE_VERSION_DEFAULT = "20"
_JVM_VERSION_DEFAULT = "21"
_RUST_VERSION_DEFAULT = "1.82"
_DOTNET_VERSION_DEFAULT = "8.0"
_RUBY_VERSION_DEFAULT = "3.3"
_PHP_VERSION_DEFAULT = "8.3"
_ELIXIR_VERSION_DEFAULT = "1.17"
_ELIXIR_OTP_DEFAULT = "27"

__all__ = ["dockerfile_contents_for"]


def dockerfile_contents_for(
    info: ProjectInfo,
    *,
    override: BuildOverride | None = None,
    from_git_clone: bool = False,
) -> str:
    """Return Dockerfile text for the given analysis (no I/O)."""
    match info.language:
        case SupportedLanguage.GO:
            return _dockerfile_go(override)
        case SupportedLanguage.PYTHON:
            return _dockerfile_python(override)
        case SupportedLanguage.JAVASCRIPT | SupportedLanguage.TYPESCRIPT:
            if from_git_clone:
                return _dockerfile_node_git_clone(override)
            return _dockerfile_node(override)
        case SupportedLanguage.JAVA:
            return _dockerfile_java(info, override)
        case SupportedLanguage.CLOJURE:
            return _dockerfile_clojure(info, override)
        case SupportedLanguage.RUST:
            return _dockerfile_rust(override)
        case SupportedLanguage.RUBY:
            return _dockerfile_ruby(override)
        case SupportedLanguage.PHP:
            return _dockerfile_php(override)
        case SupportedLanguage.DOTNET:
            return _dockerfile_dotnet(override)
        case SupportedLanguage.ELIXIR:
            return _dockerfile_elixir(override)
        case SupportedLanguage.UNKNOWN:
            raise DockerfileGenerationError(
                str(info.language),
                "cannot generate a Dockerfile without a known language",
            )
        case _:
            raise DockerfileGenerationError(
                str(info.language),
                "no built-in template for this language",
            )


def _cmd_line(default_tokens: list[str], override: BuildOverride | None) -> str:
    tokens = override.start_command if override and override.start_command else default_tokens
    return "CMD " + json.dumps(tokens)


def _language_version(override: BuildOverride | None, default: str) -> str:
    if override and override.language_version:
        return override.language_version
    return default


def _dockerfile_go(override: BuildOverride | None) -> str:
    version = _language_version(override, _GO_VERSION_DEFAULT)
    cmd = _cmd_line(["./app"], override)
    return f"""# Generated by Vela — minimal Go service image
FROM golang:{version}-alpine AS builder
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/app ./app
EXPOSE 8080
USER nobody
{cmd}
"""


def _dockerfile_python(override: BuildOverride | None) -> str:
    version = _language_version(override, _PYTHON_VERSION_DEFAULT)
    cmd = _cmd_line(["python", "-m", "http.server", "8000"], override)
    return f"""# Generated by Vela — minimal Python image
FROM python:{version}-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PIP_NO_CACHE_DIR=1
COPY . .
RUN pip install --no-cache-dir pip setuptools wheel \\
    && if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; \\
    else pip install --no-cache-dir .; fi
EXPOSE 8000
{cmd}
"""


def _dockerfile_node(override: BuildOverride | None) -> str:
    version = _language_version(override, _NODE_VERSION_DEFAULT)
    cmd = _cmd_line(
        [
            "sh",
            "-c",
            "npm run start || npm run dev || npm run preview -- --host 0.0.0.0 --port 4173",
        ],
        override,
    )
    return f"""# Generated by Vela — Node/Vite/React (start, dev, or preview)
FROM node:{version}-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
EXPOSE 3000 5173 4173
ENV NODE_ENV=development
ENV HOST=0.0.0.0
# Missing scripts must exit non-zero so ``||`` can fall through to ``dev`` / ``preview``.
{cmd}
"""


def _dockerfile_node_git_clone(override: BuildOverride | None) -> str:
    """Node template for repos cloned from Git: fixed install + dev server."""
    version = _language_version(override, _NODE_VERSION_DEFAULT)
    cmd = _cmd_line(
        ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--no-open"],
        override,
    )
    return f"""# Generated by Vela — Node from Git (npm ci + npm run dev)
FROM node:{version}-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
EXPOSE 3000 5173 4173
ENV NODE_ENV=development
ENV HOST=0.0.0.0
# Vite may try ``xdg-open`` if ``server.open`` is set; slim images have no browser.
ENV BROWSER=none
{cmd}
"""


def _resolve_java_build_tool(info: ProjectInfo, override: BuildOverride | None) -> str:
    if override and override.package_manager in ("gradle", "maven"):
        return override.package_manager
    dependency_file = (info.dependency_file or "").lower()
    if "pom.xml" in dependency_file:
        return "maven"
    return "gradle"


def _dockerfile_java(info: ProjectInfo, override: BuildOverride | None) -> str:
    version = _language_version(override, _JVM_VERSION_DEFAULT)
    cmd = _cmd_line(["java", "-jar", "app.jar"], override)

    if _resolve_java_build_tool(info, override) == "maven":
        return f"""# Generated by Vela — Java (Maven) multi-stage build
FROM maven:3.9-eclipse-temurin-{version} AS builder
WORKDIR /src
COPY . .
RUN ./mvnw -q -DskipTests package 2>/dev/null || mvn -q -DskipTests package
RUN mkdir -p /out \\
    && (find ./target -maxdepth 1 -name "*.jar" -not -name "*-plain.jar" -exec cp {{}} /out/app.jar \\; ) \\
    || find ./target -maxdepth 1 -name "*.jar" -exec cp {{}} /out/app.jar \\;

FROM eclipse-temurin:{version}-jre
WORKDIR /app
COPY --from=builder /out/app.jar ./app.jar
EXPOSE 8080
{cmd}
"""

    return f"""# Generated by Vela — Java (Gradle) multi-stage build
FROM gradle:8.10-jdk{version} AS builder
WORKDIR /src
COPY . .
RUN ./gradlew bootJar -x test --no-daemon 2>/dev/null \\
    || gradle bootJar -x test --no-daemon 2>/dev/null \\
    || ./gradlew build -x test --no-daemon 2>/dev/null \\
    || gradle build -x test --no-daemon
RUN mkdir -p /out \\
    && (find . -path "*/build/libs/*.jar" -not -name "*-plain.jar" -exec cp {{}} /out/app.jar \\; ) \\
    || find . -path "*/build/libs/*.jar" -exec cp {{}} /out/app.jar \\;

FROM eclipse-temurin:{version}-jre
WORKDIR /app
COPY --from=builder /out/app.jar ./app.jar
EXPOSE 8080
{cmd}
"""


def _resolve_clojure_tool(info: ProjectInfo, override: BuildOverride | None) -> str:
    if override and override.package_manager in ("deps", "lein"):
        return override.package_manager
    dependency_file = (info.dependency_file or "").lower()
    if "project.clj" in dependency_file:
        return "lein"
    return "deps"


def _dockerfile_clojure(info: ProjectInfo, override: BuildOverride | None) -> str:
    version = _language_version(override, _JVM_VERSION_DEFAULT)
    cmd = _cmd_line(["java", "-jar", "app.jar"], override)

    if _resolve_clojure_tool(info, override) == "lein":
        return f"""# Generated by Vela — Clojure (Leiningen) multi-stage build
FROM clojure:temurin-{version}-lein AS builder
WORKDIR /src
COPY . .
RUN lein uberjar
RUN mkdir -p /out \\
    && find ./target -name "*standalone*.jar" -exec cp {{}} /out/app.jar \\; \\
    && test -f /out/app.jar

FROM eclipse-temurin:{version}-jre
WORKDIR /app
COPY --from=builder /out/app.jar ./app.jar
EXPOSE 8080
{cmd}
"""

    return f"""# Generated by Vela — Clojure (tools.deps) multi-stage build
FROM clojure:temurin-{version}-tools-deps AS builder
WORKDIR /src
COPY . .
RUN clojure -T:build uberjar 2>/dev/null || clojure -X:uberjar
RUN mkdir -p /out \\
    && find . -name "*.jar" -not -path "*/.cpcache/*" -exec cp {{}} /out/app.jar \\; \\
    && test -f /out/app.jar

FROM eclipse-temurin:{version}-jre
WORKDIR /app
COPY --from=builder /out/app.jar ./app.jar
EXPOSE 8080
{cmd}
"""


def _dockerfile_rust(override: BuildOverride | None) -> str:
    version = _language_version(override, _RUST_VERSION_DEFAULT)
    cmd = _cmd_line(
        ["sh", "-c", "exec $(find ./bin -maxdepth 1 -type f -executable | head -n1)"],
        override,
    )
    return f"""# Generated by Vela — Rust multi-stage build
FROM rust:{version}-slim AS builder
WORKDIR /src
COPY . .
RUN cargo build --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates \\
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /src/target/release/ ./bin/
EXPOSE 8080
{cmd}
"""


def _dockerfile_ruby(override: BuildOverride | None) -> str:
    version = _language_version(override, _RUBY_VERSION_DEFAULT)
    cmd = _cmd_line(["bundle", "exec", "rackup", "-o", "0.0.0.0", "-p", "8080"], override)
    return f"""# Generated by Vela — Ruby (Bundler) image
FROM ruby:{version}-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends build-essential \\
    && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock* ./
RUN bundle install
COPY . .
EXPOSE 8080
{cmd}
"""


def _dockerfile_php(override: BuildOverride | None) -> str:
    version = _language_version(override, _PHP_VERSION_DEFAULT)
    cmd = _cmd_line(["php", "-S", "0.0.0.0:8080", "-t", "."], override)
    return f"""# Generated by Vela — PHP (Composer) built-in server
FROM php:{version}-cli
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends unzip git curl \\
    && rm -rf /var/lib/apt/lists/* \\
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
COPY composer.json composer.lock* ./
RUN composer install --no-dev --no-interaction --prefer-dist
COPY . .
EXPOSE 8080
{cmd}
"""


def _dockerfile_dotnet(override: BuildOverride | None) -> str:
    version = _language_version(override, _DOTNET_VERSION_DEFAULT)
    cmd = _cmd_line(["dotnet", "app.dll"], override)
    return f"""# Generated by Vela — .NET multi-stage build
FROM mcr.microsoft.com/dotnet/sdk:{version} AS builder
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:{version}
WORKDIR /app
COPY --from=builder /out ./
EXPOSE 8080
ENV ASPNETCORE_URLS=http://0.0.0.0:8080
{cmd}
"""


def _dockerfile_elixir(override: BuildOverride | None) -> str:
    version = _language_version(override, _ELIXIR_VERSION_DEFAULT)
    cmd = _cmd_line(["_build/prod/rel/app/bin/app", "start"], override)
    return f"""# Generated by Vela — Elixir release build
FROM elixir:{version}-otp-{_ELIXIR_OTP_DEFAULT}-slim AS builder
WORKDIR /src
ENV MIX_ENV=prod
RUN mix local.hex --force && mix local.rebar --force
COPY mix.exs mix.lock* ./
RUN mix deps.get --only prod
COPY . .
RUN mix release \\
    && test -d /src/_build/prod/rel

FROM elixir:{version}-otp-{_ELIXIR_OTP_DEFAULT}-slim
WORKDIR /app
COPY --from=builder /src/_build/prod/rel/ ./_build/prod/rel/
EXPOSE 8080
{cmd}
"""
