"""Generate Dockerfiles for projects analyzed by ``language_detection``.

``analyze_project`` is re-exported here (rather than redefined) so existing callers can keep
importing it from this module while the marker-scanning logic lives in ``language_detection``.
"""

from __future__ import annotations

from pathlib import Path

from app.core.enums import BuildStrategy, SupportedLanguage
from app.core.exceptions import DockerfileGenerationError, UnsupportedProjectError
from app.core.git.language_detection import analyze_project
from app.core.models import ProjectInfo

__all__ = [
    "analyze_project",
    "dockerfile_contents_for",
    "ensure_dockerfile_for_build",
]


def dockerfile_contents_for(
    info: ProjectInfo, *, from_git_clone: bool = False
) -> str:
    """Return Dockerfile text for the given analysis (no I/O)."""
    match info.language:
        case SupportedLanguage.GO:
            return _dockerfile_go()
        case SupportedLanguage.PYTHON:
            return _dockerfile_python()
        case SupportedLanguage.JAVASCRIPT | SupportedLanguage.TYPESCRIPT:
            if from_git_clone:
                return _dockerfile_node_git_clone()
            return _dockerfile_node()
        case SupportedLanguage.UNKNOWN:
            raise DockerfileGenerationError(
                str(info.language),
                "cannot generate a Dockerfile without a known language",
            )
        case (
            SupportedLanguage.JAVA
            | SupportedLanguage.RUST
            | SupportedLanguage.RUBY
        ):
            raise DockerfileGenerationError(
                str(info.language),
                "no built-in template for this language",
            )


def ensure_dockerfile_for_build(
    project_root: Path,
    *,
    dockerfile_name: str = "Dockerfile",
    from_git_clone: bool = False,
) -> tuple[BuildStrategy, ProjectInfo]:
    """If ``dockerfile_name`` is missing, write a generated Dockerfile; return strategy + info."""
    root = project_root.resolve()
    target = root / dockerfile_name
    info = analyze_project(root)

    if target.is_file():
        return BuildStrategy.DOCKERFILE_EXISTS, info.model_copy(
            update={"has_dockerfile": True, "dockerfile_path": dockerfile_name}
        )

    if info.language is SupportedLanguage.UNKNOWN:
        raise UnsupportedProjectError(
            "No Dockerfile in project root and no supported markers were found. "
            "Add a Dockerfile, or add one of: package.json, requirements.txt, "
            "pyproject.toml, go.mod."
        )

    try:
        body = dockerfile_contents_for(info, from_git_clone=from_git_clone)
    except DockerfileGenerationError:
        raise
    try:
        target.write_text(body, encoding="utf-8")
    except OSError as exc:
        raise DockerfileGenerationError(
            str(info.language), f"failed to write {target}: {exc}"
        ) from exc

    return BuildStrategy.GENERATED_DOCKERFILE, info.model_copy(
        update={"has_dockerfile": True, "dockerfile_path": dockerfile_name}
    )


def _dockerfile_go() -> str:
    return """# Generated by Vela — minimal Go service image
FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app .

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/app ./app
EXPOSE 8080
USER nobody
CMD ["./app"]
"""


def _dockerfile_python() -> str:
    return """# Generated by Vela — minimal Python image
FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PIP_NO_CACHE_DIR=1
COPY . .
RUN pip install --no-cache-dir pip setuptools wheel \\
    && if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; \\
    else pip install --no-cache-dir .; fi
EXPOSE 8000
CMD ["python", "-m", "http.server", "8000"]
"""


def _dockerfile_node() -> str:
    return """# Generated by Vela — Node/Vite/React (start, dev, or preview)
FROM node:20-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
EXPOSE 3000 5173 4173
ENV NODE_ENV=development
ENV HOST=0.0.0.0
# Missing scripts must exit non-zero so ``||`` can fall through to ``dev`` / ``preview``.
CMD ["sh", "-c", "npm run start || npm run dev || npm run preview -- --host 0.0.0.0 --port 4173"]
"""


def _dockerfile_node_git_clone() -> str:
    """Node template for repos cloned from Git: fixed install + dev server."""
    return """# Generated by Vela — Node from Git (npm ci + npm run dev)
FROM node:20-bookworm-slim
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
EXPOSE 3000 5173 4173
ENV NODE_ENV=development
ENV HOST=0.0.0.0
# Vite may try ``xdg-open`` if ``server.open`` is set; slim images have no browser.
ENV BROWSER=none
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--no-open"]
"""
