"""Tests for project marker detection and Dockerfile bootstrap."""

from __future__ import annotations

from pathlib import Path

import pytest

from app.core.enums import BuildStrategy, SupportedLanguage
from app.core.exceptions import AnalysisError, DockerfileGenerationError, UnsupportedProjectError
from app.core.docker_orchestrator import _is_vela_local_build_tag
from app.core.models import ProjectInfo
from app.core.project_analysis import (
    analyze_project,
    dockerfile_contents_for,
    ensure_dockerfile_for_build,
)


def test_analyze_empty_dir_unknown(tmp_path: Path) -> None:
    info = analyze_project(tmp_path)
    assert info.language is SupportedLanguage.UNKNOWN
    assert not info.has_dockerfile


def test_analyze_package_json_javascript(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text('{"name":"a"}', encoding="utf-8")
    info = analyze_project(tmp_path)
    assert info.language is SupportedLanguage.JAVASCRIPT
    assert info.dependency_file == "package.json"


def test_analyze_typescript_with_tsconfig(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    (tmp_path / "tsconfig.json").write_text("{}", encoding="utf-8")
    info = analyze_project(tmp_path)
    assert info.language is SupportedLanguage.TYPESCRIPT


def test_analyze_requirements_python(tmp_path: Path) -> None:
    (tmp_path / "requirements.txt").write_text("flask\n", encoding="utf-8")
    info = analyze_project(tmp_path)
    assert info.language is SupportedLanguage.PYTHON


def test_analyze_go_mod(tmp_path: Path) -> None:
    (tmp_path / "go.mod").write_text("module x\ngo 1.22\n", encoding="utf-8")
    info = analyze_project(tmp_path)
    assert info.language is SupportedLanguage.GO


def test_analyze_not_dir_raises(tmp_path: Path) -> None:
    f = tmp_path / "file.txt"
    f.write_text("x", encoding="utf-8")
    with pytest.raises(AnalysisError):
        analyze_project(f)


def test_ensure_dockerfile_exists_skips_write(tmp_path: Path) -> None:
    (tmp_path / "Dockerfile").write_text("FROM scratch\n", encoding="utf-8")
    (tmp_path / "package.json").write_text("{}", encoding="utf-8")
    strategy, info = ensure_dockerfile_for_build(tmp_path)
    assert strategy is BuildStrategy.DOCKERFILE_EXISTS
    assert info.has_dockerfile


def test_ensure_dockerfile_generates_for_node(tmp_path: Path) -> None:
    (tmp_path / "package.json").write_text('{"scripts":{"start":"node index.js"}}', encoding="utf-8")
    strategy, info = ensure_dockerfile_for_build(tmp_path)
    assert strategy is BuildStrategy.GENERATED_DOCKERFILE
    assert (tmp_path / "Dockerfile").read_text(encoding="utf-8").startswith("# Generated by Vela")
    assert info.has_dockerfile


def test_ensure_dockerfile_unknown_raises(tmp_path: Path) -> None:
    (tmp_path / "README.md").write_text("hi", encoding="utf-8")
    with pytest.raises(UnsupportedProjectError):
        ensure_dockerfile_for_build(tmp_path)


def test_dockerfile_contents_java_raises() -> None:
    info = ProjectInfo(language=SupportedLanguage.JAVA, has_dockerfile=False)
    with pytest.raises(DockerfileGenerationError):
        dockerfile_contents_for(info)


def test_node_dockerfile_falls_back_past_npm_start() -> None:
    body = dockerfile_contents_for(
        ProjectInfo(language=SupportedLanguage.JAVASCRIPT, has_dockerfile=False)
    )
    assert "npm run start ||" in body
    assert "npm run dev ||" in body
    assert "--if-present" not in body


def test_is_vela_local_build_tag() -> None:
    assert _is_vela_local_build_tag("vela/gitbuild:deadbeef")
    assert _is_vela_local_build_tag("Vela/Gitbuild:ABC")
    assert not _is_vela_local_build_tag("nginx:latest")
